# Generated by Django 4.2 on 2023-04-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_remove_comentario_usuario_alter_comentario_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumento',
            options={'ordering': ['usuario', '-fechaPublicacion']},
        ),
    ]
